#!/bin/sh

## Generic launcher script for Python DS.

# maps input arguments to variables with speaking names
SERVER=`basename $0`
INST=$1
shift

# prepares enviroment
SERVERPATH="$SICILIA/ds/python/BrukerEC_PS"
PYTHONPATH+=":$SERVERPATH"
CMD="/usr/bin/python BrukerEC_PS.py $INST $*"
SCREEN="screen -dmS $SERVER.$INST"

echo $SERVERPATH
echo $CMD
cd $SERVERPATH || exit 1
if [ "$INST" = "-?" ]
then
    $CMD
else
    $SCREEN $CMD
fi
